blog/urls.py
from django.urls import path
from .views import *

app_name='blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('<int:pk>/', BlogDetailview.as_view(), name='detail'),
]

proyectoBienesRaices/urls.py
from django.contrib import admin
from django.urls import path, include
from.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='Home'),
    path('blog/', include('blog.urls', namespace='Blog')),
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=250)
    content=models.TextField()
    
    def __str__(self):
        return self.title
    

blog/forms.py
from django import forms


from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','content')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from .forms import PostCreateForm
from .models import Post

# Create your views here.

class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context={
            'posts': posts
        }
        return render(request, 'blog_list.html', context)
    
class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form=PostCreateForm()
        context={
            'form':form
        }
        return render(request, 'blog_create.html', context)
    def post(self, request, *args, **kwargs):
        if request.method=='POST':
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')
                
                p, created = Post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect('blog:home')
            
            
        context={
            
        }
        return render(request, 'blog_create.html', context)
    
class BlogDetailview(View):
    def get(self, request, pk,  *args, **kwargs):
        post= get_object_or_404(Post, pk=pk)
        context={
            
            'post':post
        }
        return render(request, 'blog_details.html', context)
    

proyectoBienesRaices/views.py
from django.views.generic import View
from django.shortcuts import render

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context={
            
        }
        return render(request, 'index.html', context)

blog/templates/blog_create.html
<form method='POST'>
    {% csrf_token %}
tittle{{form.title}}
<br>

content{{form.content}}
<br>
<button type='submit'> Submit </button>
</form>

blog/templates/blog_details.html
{{post.title}}
<br>

{{post.content}}


<br>
<br>
<a href='{% url 'blog:home' %}'> Regresar </a>

blog/templates/blog_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Todos nuestros Blogs</h1>

    <br>

    {% for post in posts %}
    <br>
     <a href= {% url 'blog:detail' post.id %} > {{post.title}} </a>
    <br>
    {{post.content}}
    <br>
    {% endfor %}
    <br>

    <a href='{% url 'blog:create' %}'> Crear Nuevo Post </a>

</body>
</html>

proyectoBienesRaices/templates/index.html
Hola visita mi blog: <a href="{% url 'blog:home' %}"> Blog Aqui </a>